{{- if .Values.gateway.enabled }}

apiVersion: networking.istio.io/v1

kind: Gateway

metadata:
  name: {{ .Release.Name }}

spec:

  selector:
    istio: {{ .Values.gateway.gatewaySelector }}

  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP

    hosts:
    - "*"

{{- end }}