service:
  annotations:
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/backend-protocol: "tcp"
    alb.ingress.kubernetes.io/connection-idle-timeout: "3600"
    alb.ingress.kubernetes.io/ssl-cert: "arn:aws:acm:ap-south-1:729859598223:certificate/c0bfa19b-6edb-4f34-819b-dff163225ee4"
    alb.ingress.kubernetes.io/ssl-ports: "443"