service:
  annotations:
    kubernetes.io/ingress.class: alb

    alb.ingress.kubernetes.io/scheme: internet-facing

    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/listen-ports: |
      [
        {"HTTP":80},
        {"HTTPS":443}
      ]

    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:729859598223:certificate/8add2211-a513-4abd-9ae8-cee195411a70

    alb.ingress.kubernetes.io/ssl-redirect: '443'