service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ip"
    # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-south-1:729859598223:certificate/8add2211-a513-4abd-9ae8-cee195411a70"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    
  ports:

    - name: status-port
      port: 15021
      targetPort: 15021

    - name: http2
      port: 80
      targetPort: 80

    - name: https
      port: 443
      targetPort: 80