apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: applications
spec:
  gateways:
  - {{ .Values.gateway.name }}
  hosts:
  - "*"
  http:

{{- range .Values.applications }}

  - match:

    - uri:

        prefix: {{ .path }}

    rewrite:

      uri: /

    route:

    - destination:

        host: {{ .name }}

        port:

          number: {{ .servicePort }}

{{- end }}