name: infra-pipeline

on:
  workflow_dispatch:

jobs:
  init-validate:
    name: Init & Validate
    runs-on: ubuntu-latest
    environment:
      name: AWS-credentials
    env:
      TF_VERSION: 'latest'
      TF_DIR: ${{ github.workspace }}
      TFSTATE_BUCKET: rsrinfra-lockfile
      TFSTATE_PREFIX: dev
      ENV: rsr
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init (S3 backend)
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ env.TFSTATE_BUCKET }}" \
            -backend-config="key=${{ env.TFSTATE_PREFIX }}/${{ env.ENV }}-terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
          # terraform import -input=false -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars helm_release.aws_lbc kube-system/aws-load-balancer-controller || true
          # terraform import -input=false -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars helm_release.metrics_server kube-system/metrics-server || true
          # terraform import -input=false -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars helm_release.cluster_autoscaler kube-system/cluster-autoscaler || true
          # terraform import -input=false -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars helm_release.istiod istio-system/istiod || true
          terraform import -input=false -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars helm_release.istio_ingress istio-ingress/istio-ingress || true
          terraform import -input=false -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars helm_release.istio_ingress-internal istio-ingress-internal/istio-ingress-internal || true
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}
      
      - name: Terraform plan
        run: terraform plan -out=tfplan -var-file=variables-${{ env.TFSTATE_PREFIX }}.tfvars 
        working-directory: ${{ env.TF_DIR }}
 
      - name: Terraform apply
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: ${{ env.TF_DIR }}
      
      # - name: Terrafrom destroy
      #   run: terraform destroy -auto-approve
      #   working-directory: ${{ env.TF_DIR }}
        


